### PR TITLE
Fix translations in discussion list search page

### PR DESCRIPTION
**Pull request by fredvd**

### CODE REVIEW

**Comment by fredvd** [comment]
Needs some more work, made a typo somewhere

**Comment by cekk** [comment]
ok ;)

**Comment by fredvd** [comment]
@cekk Reopened, false alarm. I had issues with some translations, but my .mo files where somehow not compiled correctly when I made an internal release.

**Comment by cekk** [comment]
perfect, thanks!
I'll update Italian translations and then make a release.

**Pull request merged**
