### PR TITLE
Bugfix (isAnon didn't work for me) and formatting

### PR DESCRIPTION
**Pull request by tobiasherp**
Adding this product made my comments workflow work, so I consider it useful.
Sadly, discussion_list_search didn't work because of missing `isAnon`.
Before applying functional changes I rectified the whitespace ...

There is some small TAL refactoring as well;
and I pep8ified the Python files.

### CODE REVIEW

**Comment by cekk** [comment]
Yes, the original workflow was a bit buggy, so we fixed it in this package.
If you update also the changelog, i can merge it, and make a new release.

Thanks for the fixes!

**Comment by tobiasherp** [comment]
Ok, I added a few lines; feel free to adjust them to your needs. Thank you!

**Comment by tobiasherp** [comment]
Btw., since the original `comment_review_workflow` is buggy -- shouldn't we make a pull request to have it fixed? Otherwise there are two workflows almost sure to exist, which are named the same but in fact behave very differently ... and the one installed last wins, right?

As far I can see, the `plone.app.discussion` version has `i18n` attributes added meanwhile.
Perhaps we should adapt this in our version and then make an educated suggestion to change the original.

**Comment by cekk** [comment]
Released also on pypi. Thanks for your help!

And btw, yes, the last installed wins but in Plone > 4 p.a.comments is already installed, so this product is always the last ;)

I agree with you that should be a good thing to fix the workflow directly on the default package (p.a.discussion) and not here. This was an old and quick workaround.
Feel free to propose some changes on the original product (i don't know if maybe they've already fixed it) or improvements in ours.

**Pull request merged**
