### PR TITLE
Drop Plone 3 and 4, add Plone 5 and 6.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
This is only initial support.
The Plone 6 instance I am trying this in has other packages which do not start yet.
But at least all ImportErrors seem gone, and we no longer use zope.formlib.
May need a different widget.

Current stable version is for Plone 4 and does not work on 5.
I want it to work on Plone 6, and will use `collective.exportimport` to directly go there.
But in order to have a more standard migration path, a new version should support Plone 5.2 on Python 2 as well.
This PR does that.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Update: Plone 6 starts now, but the add form of the portlet does not show. We indeed need a different widget:

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 376, in publish_module
  Module ZPublisher.WSGIPublisher, line 271, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module plone.app.portlets.browser.formhelper, line 59, in __call__
  Module z3c.form.form, line 233, in __call__
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 132, in update
  Module z3c.form.form, line 136, in updateWidgets
  Module z3c.form.field, line 274, in update
  Module z3c.form.browser.select, line 51, in update
  Module z3c.form.browser.widget, line 171, in update
  Module z3c.form.widget, line 233, in update
  Module z3c.form.widget, line 225, in updateTerms
  Module zope.component._api, line 104, in getMultiAdapter
zope.interface.interfaces.ComponentLookupError: ((<+ at /Plone/++contextportlets++plone.rightcolumn/+>, <WSGIRequest, URL=http://localhost:9030/Plone/++contextportlets++plone.rightcolumn/+/collective.portlet.discussion.DiscussionPortlet>, <Products.Five.browser.metaconfigure.AddForm object at 0x10cd5a1f0>, <zope.schema._field.Choice object at 0x10be7f4c0 collective.portlet.discussion.discussionportlet.IDiscussionPortlet.discussionFolder>, <SelectWidget 'form.widgets.discussionFolder'>), <InterfaceClass z3c.form.interfaces.ITerms>, '')
```

**Comment by mauritsvanrees** [comment]
It is working now on Plone 6, so can be reviewed.
I should still test on Plone 5.2, though I expect it to work.

**Comment by mauritsvanrees** [comment]
I have updated the tests. Really ready now.

Perhaps one open question is what to do with the comment workflows that are defined in this package. I guess they could be removed in favour of the standard ones from `plone.app.discussion`. But that can be a separate issue, to not make this PR too large.

**Comment by mauritsvanrees** [comment]
I have made a [separate issue](https://github.com/RedTurtle/collective.portlet.discussion/issues/6) for the workflows.

@cekk has done the most commits on this package. Can you review please?

**Comment by cekk** [comment]
Changes LGTM. We're not using this portlet anymore, so if you need these changes feel free to fix whatever you want.

You can also remove workflow definitions: probably they come from a previous Plone version (maybe 3?)

**Comment by mauritsvanrees** [comment]
So how should we continue? Shall I fork this to the Collective? Then I can merge it myself.

And could you grant [PyPI permissions](https://pypi.org/project/collective.portlet.discussion/) to user `maurits` and/or `collective` please? Then I can make releases.

**Comment by cekk** [comment]
Whatever yo want is fine for me. Maybe could be better to move directly this repo into collective? I'm ok with this.

Sent invites for pypi too.

**Comment by mauritsvanrees** [comment]
I have copied the code to https://github.com/collective/collective.portlet.discussion
Thanks for the cooperation and thanks for this product!

**Pull request closed without merging**
